name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  binaries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Binaries Release
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          version: 'latest'
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
